title: <p align="left"> Amy Anh Hoang </p>

logo: "/images/photo.png?raw=true"

description:
  <p align="center">
  <a href="https://public.tableau.com/app/profile/amy.hoang02">Tableau Portfolio</a> |
  <a href="https://www.linkedin.com/in/amy-anh-bui/">LinkedIn</a> |
  <a href="https://github.com/amyhoang02">GitHub</a>
  </p>
  
 <p align="justify">
  I am a certified Applied Business Intelligence from Toronto Institute of Data Science & Technology. 
  <br><br>
  I am currently a Credit Analyst at Flexiti Financial who is well-equipped with understanding of customer credit-worthiness and ability to analyze financial health.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
